# Generated by Django 2.0.3 on 2018-05-13 16:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=255)),
                ('body', tinymce.models.HTMLField()),
                ('image', models.FileField(default='t20-cricket.jpg', upload_to='')),
            ],
        ),
    ]
