# Generated by Django 2.0.3 on 2018-06-21 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('opponents', models.CharField(default='Add Opponents', max_length=255)),
                ('slug', models.SlugField(default='', editable=False, max_length=255)),
                ('prediction', models.CharField(blank=True, max_length=50)),
                ('winner', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('No Result', 'No Result')], default='No Result', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'All Matches',
                'ordering': ['-date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.TextField(max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
            ],
            options={
                'verbose_name_plural': 'All Messages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('title', models.CharField(default='Enter Series Title', max_length=255)),
                ('series_slug', models.SlugField(default='', editable=False, max_length=255)),
                ('series_image', models.FileField(default='game.png', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'All Series',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Series'),
        ),
    ]
