# Generated by Django 2.0.6 on 2018-07-04 05:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('opponents', models.CharField(default='Add Opponents', max_length=255)),
                ('slug', models.SlugField(default='', editable=False, max_length=255)),
                ('prediction', models.CharField(blank=True, max_length=50)),
                ('winner', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('no result', 'No Result')], default='no result', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.TextField(max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Enter Series Title', max_length=255)),
                ('series_slug', models.SlugField(default='', editable=False, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('series_image', models.FileField(default='game.png', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Series'),
        ),
    ]
