# Generated by Django 2.0.3 on 2018-06-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('no result', 'No Result')], default='no result', max_length=10),
        ),
    ]
