# Generated by Django 2.0.3 on 2018-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='body',
            field=models.TextField(default='Add content'),
        ),
    ]
