# Generated by Django 2.0.6 on 2018-07-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20180705_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_score',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_score',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
