# Generated by Django 2.0.3 on 2018-05-14 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20180513_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='body',
        ),
        migrations.RemoveField(
            model_name='match',
            name='title',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.CharField(default='Add tournament details', max_length=255),
        ),
    ]
