# Generated by Django 2.0.3 on 2018-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20180514_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='opponents',
            field=models.CharField(default='Opponents', max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('UP', 'Upcoming'), ('RE', 'Recent')], default='UP', max_length=2),
        ),
    ]
