# Generated by Django 2.0.6 on 2018-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20180705_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
