# Generated by Django 2.0.6 on 2018-07-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('live', 'live'), ('completed', 'completed')], default='not started', max_length=12),
        ),
    ]
