# Generated by Django 2.0.3 on 2018-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20180514_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='image',
        ),
        migrations.AddField(
            model_name='match',
            name='prediction',
            field=models.CharField(default='Not Updated', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('N', 'No Result')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(default='Not Updated', max_length=50),
        ),
    ]
