# Generated by Django 2.0.6 on 2018-07-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tags',
            field=models.ManyToManyField(blank=True, to='match.Tag'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('live', 'Live'), ('completed', 'Completed')], default='not started', max_length=12),
        ),
    ]
