# Generated by Django 2.0.6 on 2018-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20180710_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bookie',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_odds',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_odds',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
