# Generated by Django 2.0.3 on 2018-05-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='t_name',
            new_name='tournament',
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Tournament'),
        ),
    ]
