# Generated by Django 2.0.6 on 2018-07-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20180726_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='odds_team_a_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_team_b_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
