# Generated by Django 2.0.3 on 2018-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_tournament_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
