# Generated by Django 2.0.3 on 2018-05-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20180514_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='slug',
            new_name='t_slug',
        ),
    ]
