# Generated by Django 2.0.3 on 2018-05-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20180514_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='t_slug',
            new_name='slug',
        ),
    ]
