# Generated by Django 2.0.3 on 2018-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_auto_20180514_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
