# Generated by Django 2.0.3 on 2018-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_match_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
