# Generated by Django 2.0.3 on 2018-05-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_auto_20180516_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
