# Generated by Django 2.0.3 on 2018-05-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_auto_20180516_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='slug',
            new_name='t_slug',
        ),
    ]
