# Generated by Django 2.0.3 on 2018-05-19 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_auto_20180519_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.CharField(default='Admin message', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
    ]
