# Generated by Django 2.0.3 on 2018-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0017_auto_20180519_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('No Result', 'No Result')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Recent', 'Recent')], default='UP', max_length=8),
        ),
    ]
