# Generated by Django 2.0.3 on 2018-05-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0018_auto_20180520_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='summary',
            field=models.TextField(blank=True, default='Summary'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='t_image',
            field=models.FileField(default='media/game.png', upload_to=''),
        ),
    ]
