# Generated by Django 2.0.3 on 2018-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0019_auto_20180524_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='t_image',
            field=models.FileField(default='game.png', upload_to=''),
        ),
    ]
