# Generated by Django 2.0.3 on 2018-05-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0020_auto_20180524_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Enter Tournament Title', max_length=255)),
                ('series_slug', models.SlugField(default='', editable=False, max_length=255)),
                ('summary', models.TextField(blank=True, default='Summary')),
                ('series_image', models.FileField(default='game.png', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Upcoming', 'Upcoming'), ('Recent', 'Recent')], default='UP', max_length=8),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='match.Series'),
            preserve_default=False,
        ),
    ]
