# Generated by Django 2.0.3 on 2018-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_auto_20180528_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('No Result', 'No Result')], default='No Result', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Upcoming', 'Upcoming'), ('Recent', 'Recent')], default='Upcoming', max_length=8),
        ),
    ]
