# Generated by Django 2.0.3 on 2018-06-06 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0023_auto_20180531_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
