# Generated by Django 2.0.3 on 2018-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0024_auto_20180607_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date', 'time'], 'verbose_name_plural': 'MATCH SCHEDULE'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date'], 'verbose_name_plural': 'MESSAGES'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-date'], 'verbose_name_plural': 'ALL SERIES'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.AddField(
            model_name='match',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
