# Generated by Django 2.0.3 on 2018-06-18 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_auto_20180618_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
