# Generated by Django 2.0.3 on 2018-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_auto_20180618_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=255),
        ),
    ]
