# Generated by Django 2.0.3 on 2018-06-18 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0026_auto_20180618_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
