# Generated by Django 2.0.3 on 2018-06-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0026_auto_20180619_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='series',
            name='summary',
        ),
    ]
