# Generated by Django 2.0.3 on 2018-06-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0027_auto_20180620_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date', 'time'], 'verbose_name_plural': 'All Matches'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date'], 'verbose_name_plural': 'All Messages'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-date'], 'verbose_name_plural': 'All Series'},
        ),
        migrations.AlterField(
            model_name='match',
            name='opponents',
            field=models.CharField(default='Add Opponents', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='prediction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(default='Enter Series Title', max_length=255),
        ),
    ]
